apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kubelet-serving"]
  verbs: ["approve"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["create"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  resourceNames: ["guestcluster-quota-validator"]
  verbs: ["get", "delete", "update"]
- apiGroups: ["provisioning.cattle.io"]
  resources:
  - clusters
  verbs: ["get", "list"]
- apiGroups: ["rke-machine-config.cattle.io"]
  resources:
  - harvesterconfigs
  verbs: ["get", "list"]
