apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}-cabundle
  namespace: "kube-system"
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kube-root-ca.crt"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}-kubeconfig-read
  namespace: fleet-default
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}-cc-read
  namespace: cattle-global-data
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
