{{- if .Values.guestclusterquotawebhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guestcluster-quota-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
  {{- with .Values.guestclusterquotawebhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
