apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "guestcluster-quota-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "guestcluster-quota-webhook.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
      scheme: http
  jobLabel: jobLabel
  selector:
    matchLabels:
      {{- include "guestcluster-quota-webhook.selectorLabels" . | nindent 8 }}
